# aegisai.spec
# -*- mode: python ; coding: utf-8 -*-
import os
import sys

block_cipher = None

a = Analysis(
    ['server/app/main.py'],
    pathex=['server'],
    binaries=[],
    datas=[
        ('client/dist', 'client/dist'),
        ('server/app/ml/models/*.onnx', 'server/app/ml/models'),
        ('server/app/ml/models/model_manifest.json', 'server/app/ml/models'),
        ('server/config.yaml', 'server'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'pystray',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'aiosqlite',
        'onnxruntime',
        'shap',
        'psutil',
        'loguru',
        'fastapi',
        'fastapi.staticfiles',
        'fastapi.middleware.cors',
        'fastapi.security',
        'starlette',
        'starlette.staticfiles',
        'starlette.middleware.cors',
        'starlette.responses',
        'yaml',
        'pydantic',
        'pydantic_settings',
        'jose',
        'jose.jwt',
        'passlib',
        'passlib.handlers.sha2_crypt',
        'multipart',
        'python_multipart',
        'app.api.routes.auth',
        'app.api.routes.telemetry',
        'app.api.routes.threats',
        'app.api.routes.actions',
        'app.api.routes.model',
        'app.api.routes.deception',
        'app.api.routes.agent',
        'app.api.routes.quorum',
        'app.api.routes.audit',
        'app.core.quorum',
        'app.core.sandbox',
        'app.api.websockets',
        'app.collector.tray_agent',
        'app.collector.host_monitor',
        'app.deception.honeypot_emulator',
        'app.deception.trap_logger',
        'app.ml.inference',
        'app.ml.preprocessor',
        'app.ml.xai_explainer',
        'app.agents',
        'app.agents.schemas',
        'app.agents.event_bus',
        'app.agents.detector',
        'app.agents.investigator',
        'app.agents.remediator',
        'app.agents.auditor',
        'app.agents.orchestrator',
        'app.agents.incident_agent',
        'app.agents.state',
        'app.services',
        'app.services.deception',
        'app.services.aws_service',
        'boto3',
        'botocore',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AegisAI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='client/public/favicon.ico'
)
